DELETE FROM [dbo].[pokemons_pokemon_types];
DELETE FROM [dbo].[pokemon_type];
DELETE FROM [dbo].[pokemon];

DBCC CHECKIDENT ('[pokemon_type]', RESEED, 0);
GO
DBCC CHECKIDENT ('[pokemon]', RESEED, 0);
GO

INSERT INTO [dbo].[pokemon_type] (pokemon_type_name) VALUES ('normal');
INSERT INTO [dbo].[pokemon_type] (pokemon_type_name) VALUES ('fighting');
INSERT INTO [dbo].[pokemon_type] (pokemon_type_name) VALUES ('flying');
INSERT INTO [dbo].[pokemon_type] (pokemon_type_name) VALUES ('poison');
INSERT INTO [dbo].[pokemon_type] (pokemon_type_name) VALUES ('ground');
INSERT INTO [dbo].[pokemon_type] (pokemon_type_name) VALUES ('rock');
INSERT INTO [dbo].[pokemon_type] (pokemon_type_name) VALUES ('bug');
INSERT INTO [dbo].[pokemon_type] (pokemon_type_name) VALUES ('ghost');
INSERT INTO [dbo].[pokemon_type] (pokemon_type_name) VALUES ('steel');
INSERT INTO [dbo].[pokemon_type] (pokemon_type_name) VALUES ('fire');
INSERT INTO [dbo].[pokemon_type] (pokemon_type_name) VALUES ('water');
INSERT INTO [dbo].[pokemon_type] (pokemon_type_name) VALUES ('grass');
INSERT INTO [dbo].[pokemon_type] (pokemon_type_name) VALUES ('electric');
INSERT INTO [dbo].[pokemon_type] (pokemon_type_name) VALUES ('psychic');
INSERT INTO [dbo].[pokemon_type] (pokemon_type_name) VALUES ('ice');
INSERT INTO [dbo].[pokemon_type] (pokemon_type_name) VALUES ('dragon');
INSERT INTO [dbo].[pokemon_type] (pokemon_type_name) VALUES ('dark');
INSERT INTO [dbo].[pokemon_type] (pokemon_type_name) VALUES ('fairy');
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('bulbasaur', 69, 7);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (1, 12);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (1, 4);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('ivysaur', 130, 10);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (2, 12);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (2, 4);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('venusaur', 1000, 20);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (3, 12);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (3, 4);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('charmander', 85, 6);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (4, 10);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('charmeleon', 190, 11);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (5, 10);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('charizard', 905, 17);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (6, 10);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (6, 3);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('squirtle', 90, 5);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (7, 11);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('wartortle', 225, 10);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (8, 11);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('blastoise', 855, 16);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (9, 11);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('caterpie', 29, 3);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (10, 7);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('metapod', 99, 7);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (11, 7);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('butterfree', 320, 11);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (12, 7);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (12, 3);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('weedle', 32, 3);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (13, 7);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (13, 4);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('kakuna', 100, 6);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (14, 7);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (14, 4);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('beedrill', 295, 10);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (15, 7);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (15, 4);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('pidgey', 18, 3);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (16, 1);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (16, 3);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('pidgeotto', 300, 11);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (17, 1);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (17, 3);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('pidgeot', 395, 15);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (18, 1);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (18, 3);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('rattata', 35, 3);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (19, 1);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('raticate', 185, 7);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (20, 1);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('spearow', 20, 3);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (21, 1);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (21, 3);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('fearow', 380, 12);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (22, 1);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (22, 3);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('ekans', 69, 20);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (23, 4);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('arbok', 650, 35);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (24, 4);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('pikachu', 60, 4);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (25, 13);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('raichu', 300, 8);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (26, 13);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('sandshrew', 120, 6);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (27, 5);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('sandslash', 295, 10);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (28, 5);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('nidoran-f', 70, 4);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (29, 4);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('nidorina', 200, 8);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (30, 4);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('nidoqueen', 600, 13);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (31, 4);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (31, 5);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('nidoran-m', 90, 5);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (32, 4);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('nidorino', 195, 9);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (33, 4);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('nidoking', 620, 14);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (34, 4);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (34, 5);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('clefairy', 75, 6);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (35, 18);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('clefable', 400, 13);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (36, 18);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('vulpix', 99, 6);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (37, 10);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('ninetales', 199, 11);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (38, 10);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('jigglypuff', 55, 5);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (39, 1);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (39, 18);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('wigglytuff', 120, 10);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (40, 1);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (40, 18);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('zubat', 75, 8);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (41, 4);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (41, 3);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('golbat', 550, 16);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (42, 4);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (42, 3);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('oddish', 54, 5);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (43, 12);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (43, 4);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('gloom', 86, 8);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (44, 12);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (44, 4);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('vileplume', 186, 12);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (45, 12);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (45, 4);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('paras', 54, 3);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (46, 7);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (46, 12);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('parasect', 295, 10);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (47, 7);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (47, 12);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('venonat', 300, 10);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (48, 7);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (48, 4);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('venomoth', 125, 15);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (49, 7);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (49, 4);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('diglett', 8, 2);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (50, 5);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('dugtrio', 333, 7);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (51, 5);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('meowth', 42, 4);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (52, 1);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('persian', 320, 10);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (53, 1);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('psyduck', 196, 8);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (54, 11);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('golduck', 766, 17);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (55, 11);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('mankey', 280, 5);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (56, 2);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('primeape', 320, 10);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (57, 2);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('growlithe', 190, 7);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (58, 10);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('arcanine', 1550, 19);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (59, 10);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('poliwag', 124, 6);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (60, 11);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('poliwhirl', 200, 10);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (61, 11);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('poliwrath', 540, 13);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (62, 11);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (62, 2);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('abra', 195, 9);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (63, 14);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('kadabra', 565, 13);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (64, 14);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('alakazam', 480, 15);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (65, 14);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('machop', 195, 8);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (66, 2);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('machoke', 705, 15);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (67, 2);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('machamp', 1300, 16);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (68, 2);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('bellsprout', 40, 7);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (69, 12);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (69, 4);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('weepinbell', 64, 10);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (70, 12);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (70, 4);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('victreebel', 155, 17);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (71, 12);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (71, 4);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('tentacool', 455, 9);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (72, 11);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (72, 4);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('tentacruel', 550, 16);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (73, 11);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (73, 4);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('geodude', 200, 4);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (74, 6);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (74, 5);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('graveler', 1050, 10);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (75, 6);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (75, 5);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('golem', 3000, 14);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (76, 6);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (76, 5);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('ponyta', 300, 10);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (77, 10);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('rapidash', 950, 17);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (78, 10);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('slowpoke', 360, 12);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (79, 11);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (79, 14);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('slowbro', 785, 16);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (80, 11);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (80, 14);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('magnemite', 60, 3);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (81, 13);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (81, 9);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('magneton', 600, 10);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (82, 13);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (82, 9);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('farfetchd', 150, 8);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (83, 1);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (83, 3);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('doduo', 392, 14);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (84, 1);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (84, 3);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('dodrio', 852, 18);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (85, 1);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (85, 3);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('seel', 900, 11);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (86, 11);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('dewgong', 1200, 17);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (87, 11);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (87, 15);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('grimer', 300, 9);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (88, 4);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('muk', 300, 12);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (89, 4);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('shellder', 40, 3);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (90, 11);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('cloyster', 1325, 15);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (91, 11);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (91, 15);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('gastly', 1, 13);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (92, 8);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (92, 4);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('haunter', 1, 16);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (93, 8);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (93, 4);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('gengar', 405, 15);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (94, 8);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (94, 4);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('onix', 2100, 88);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (95, 6);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (95, 5);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('drowzee', 324, 10);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (96, 14);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('hypno', 756, 16);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (97, 14);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('krabby', 65, 4);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (98, 11);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('kingler', 600, 13);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (99, 11);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('voltorb', 104, 5);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (100, 13);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('electrode', 666, 12);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (101, 13);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('exeggcute', 25, 4);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (102, 12);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (102, 14);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('exeggutor', 1200, 20);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (103, 12);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (103, 14);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('cubone', 65, 4);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (104, 5);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('marowak', 450, 10);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (105, 5);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('hitmonlee', 498, 15);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (106, 2);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('hitmonchan', 502, 14);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (107, 2);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('lickitung', 655, 12);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (108, 1);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('koffing', 10, 6);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (109, 4);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('weezing', 95, 12);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (110, 4);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('rhyhorn', 1150, 10);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (111, 5);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (111, 6);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('rhydon', 1200, 19);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (112, 5);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (112, 6);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('chansey', 346, 11);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (113, 1);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('tangela', 350, 10);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (114, 12);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('kangaskhan', 800, 22);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (115, 1);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('horsea', 80, 4);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (116, 11);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('seadra', 250, 12);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (117, 11);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('goldeen', 150, 6);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (118, 11);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('seaking', 390, 13);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (119, 11);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('staryu', 345, 8);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (120, 11);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('starmie', 800, 11);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (121, 11);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (121, 14);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('mr-mime', 545, 13);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (122, 14);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (122, 18);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('scyther', 560, 15);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (123, 7);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (123, 3);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('jynx', 406, 14);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (124, 15);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (124, 14);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('electabuzz', 300, 11);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (125, 13);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('magmar', 445, 13);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (126, 10);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('pinsir', 550, 15);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (127, 7);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('tauros', 884, 14);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (128, 1);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('magikarp', 100, 9);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (129, 11);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('gyarados', 2350, 65);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (130, 11);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (130, 3);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('lapras', 2200, 25);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (131, 11);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (131, 15);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('ditto', 40, 3);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (132, 1);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('eevee', 65, 3);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (133, 1);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('vaporeon', 290, 10);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (134, 11);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('jolteon', 245, 8);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (135, 13);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('flareon', 250, 9);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (136, 10);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('porygon', 365, 8);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (137, 1);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('omanyte', 75, 4);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (138, 6);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (138, 11);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('omastar', 350, 10);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (139, 6);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (139, 11);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('kabuto', 115, 5);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (140, 6);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (140, 11);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('kabutops', 405, 13);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (141, 6);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (141, 11);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('aerodactyl', 590, 18);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (142, 6);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (142, 3);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('snorlax', 4600, 21);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (143, 1);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('articuno', 554, 17);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (144, 15);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (144, 3);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('zapdos', 526, 16);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (145, 13);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (145, 3);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('moltres', 600, 20);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (146, 10);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (146, 3);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('dratini', 33, 18);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (147, 16);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('dragonair', 165, 40);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (148, 16);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('dragonite', 2100, 22);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (149, 16);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (149, 3);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('mewtwo', 1220, 20);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (150, 14);
INSERT INTO [dbo].[pokemon] (pokemon_name, pokemon_weight, pokemon_height) VALUES ('mew', 40, 4);
INSERT INTO [dbo].[pokemons_pokemon_types] (pokemon_id, pokemon_type_id) VALUES (151, 14);

